const list = [
  {
    id: 1,
    title: "Basic Computer Course",
    author: "Vivek Singh",
    price: 250,
    img: "https://m.media-amazon.com/images/I/513owrzb9OL.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Visual JavaScript",
    author: "Vivek Singh",
    price: 300,
    img: "https://images-na.ssl-images-amazon.com/images/I/51VDXRY03ML.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Computer Awareness",
    author: "Nitesh Singh",
    price: 290,
    img: "https://rukminim1.flixcart.com/image/416/416/kjd6nww0-0/book/i/g/n/objective-computer-awareness-original-imafyxsaknj277jh.jpeg?q=70",
    amount: 1,
  },
  {
    id: 4,
    title: "Your personal Computer",
    author: "Gautam Rathoud",
    price: 280,
    img: "https://3.imimg.com/data3/PP/XJ/MY-6716630/your-personal-computer-500x500.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Computer Basics",
    author: "Sumit",
    price: 149,
    img: "https://images-na.ssl-images-amazon.com/images/I/51WwfquQpXL.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Basic Computer course",
    author: "Rahul",
    price: 250,
    img: "https://computechpublications.in/wp-content/uploads/2018/08/669-2_bcc_it_book-ENGLISH.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Pre-School Activities Pack ",
    author: "by Om Books Editorial Team  | 1 January 2021",
    price: 693,
    img: "https://images-na.ssl-images-amazon.com/images/I/51IENRwUhKL._SX404_BO1,204,203,200_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "JavaScript",
    author: "Vivek Singh",
    price: 289,
    img: "https://res.cloudinary.com/practicaldev/image/fetch/s--A-wWbPct--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://www.daolf.com/images/js_book_list/24.jpg%23center",
    amount: 1,
  },
  {
    id: 9,
    title: "Object Orinted Programming",
    author: "Nitesh Singh",
    price: 280,
    img: "https://images.tutorialedge.net/books/object-oriented-javascript.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "JavaScript Data Structures And Algorithm",
    author: "Gautam Rathoud",
    price: 586,
    img: "https://itbook.store/img/books/9781484239872.png",
    amount: 1,
  },
  {
    id: 11,
    title: "Willy The Silly Panda",
    author: "Kapil Singh",
    price: 120,
    img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "JavaScript",
    author: "Vivek Singh",
    price: 357,
    img: "https://m.media-amazon.com/images/I/51y3NbpHTAS._SL500_.jpg",
    amount: 1,
  },
];

export default list;
